import { AppStoreButton, MobileDownload, SiteFooter, SiteHeader } from "./components/site-chrome";

export default function Home() {
  return <main id="top"><SiteHeader />
    <section className="hero home-hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span /> A smarter feed is one tap away</p><h1 id="hero-title">Your next scroll<br />can make you <em>smarter.</em></h1><p className="hero-lead">Watch one quick lesson, answer one question, and leave with something useful you can actually remember.</p><div className="hero-actions"><AppStoreButton label="Download free on the" /><a className="text-link" href="/product"><span aria-hidden="true">▶</span> Explore the product</a></div><div className="trust-row"><span><b>★</b> 4.7 from early ratings</span><span><b>✓</b> Free to download</span><span><b>✓</b> iPhone &amp; iPad</span></div></div><div className="hero-visual" aria-label="Krumbit turns a quick video into a remembered idea"><div className="hero-grid" aria-hidden="true" /><div className="hero-glow" aria-hidden="true" /><figure className="hero-phone"><img src="/screen-learn.webp" alt="Krumbit feed showing a short visual astronomy lesson" /></figure><div className="lesson-chip chip-top"><span>42 sec</span><div><small>ONE QUICK LESSON</small><strong>How galaxies begin</strong></div></div><div className="lesson-chip chip-middle"><span>?</span><div><small>ONE QUICK CHECK</small><strong>What held the idea together?</strong></div></div><div className="lesson-chip chip-bottom"><span>✓</span><div><small>KNOWLEDGE LOCKED IN</small><strong>Quiz complete · +25 XP</strong></div></div></div></section>
    <section className="result-strip"><p><strong>Watch.</strong> Recall. <em>Keep the idea.</em></p><span>Learning that fits the minutes you already have.</span></section>
    <section className="replacement section-shell home-overview"><div className="section-heading"><p className="section-label">THE KRUMBIT LOOP</p><h2>Familiar rhythm.<br /><em>A better result.</em></h2><p>Three simple steps turn passive screen time into active learning.</p></div><div className="outcome-grid"><article><span>01</span><h3>Watch something useful</h3><p>Short visual lessons make a new idea easy to enter and quick to finish.</p></article><article><span>02</span><h3>Recall it once</h3><p>A fast question asks your brain to retrieve the idea while it is fresh.</p></article><article><span>03</span><h3>See progress grow</h3><p>Quizzes, XP, streaks, and topic history make the habit visible.</p></article></div><a className="section-link" href="/product">See how the product works →</a></section>
    <section className="home-paths section-shell"><article><p className="section-label">FOR LEARNERS</p><h2>Krumbit on iPhone and iPad</h2><p>Replace the feed you forget with lessons, quick recall, and progress you can see.</p><a href="/product">Explore Krumbit →</a></article><article><p className="section-label">FOR ORGANIZATIONS</p><h2>A learning feed shaped around your audience</h2><p>Explore a customized Krumbit experience built around your topics, content, and goals.</p><a href="/solutions">Explore custom solutions →</a></article></section>
    <section className="home-review section-shell"><p className="section-label">EARLY APP STORE REVIEW</p><blockquote>“An educational version of Instagram and much better than doomscrolling. Highly recommended.”</blockquote><span>★★★★★ · App Store review</span></section>
    <section className="final-cta"><img src="/krumbit-icon.png" alt="" /><p className="section-label">YOUR NEXT SWIPE</p><h2>Open a feed.<br />Leave with something useful.</h2><p>Download Krumbit free and make the next five minutes count.</p><AppStoreButton label="Download free on the" /></section>
    <SiteFooter /><MobileDownload />
  </main>;
}
