import { SiteFooter, SiteHeader } from "../components/site-chrome";

export const metadata = { title: "Custom Learning Solutions — Krumbit", description: "Explore a customized Krumbit learning feed shaped around your audience, content, and goals." };

export default function Solutions() {
  return <main><SiteHeader /><section className="page-hero section-shell"><p className="section-label">CUSTOM SOLUTIONS</p><h1>Your knowledge.<br /><em>A feed people want to use.</em></h1><p>Krumbit can shape its short-form learning experience around an organization&apos;s audience, subject matter, and learning goals.</p><a className="primary-link" href="mailto:info@krumbit.co?subject=Custom%20Krumbit%20solution">Start a conversation →</a></section>
    <section className="solution-grid section-shell"><article><span>01</span><h2>Audience-specific learning</h2><p>Define who the experience is for and what they should understand, practice, or remember.</p></article><article><span>02</span><h2>Custom topics and content</h2><p>Organize a learning feed around the subject areas and source material that matter to your organization.</p></article><article><span>03</span><h2>Branded experience</h2><p>Explore a presentation aligned with your brand while keeping Krumbit&apos;s watch, recall, and progress loop.</p></article><article><span>04</span><h2>Progress-oriented design</h2><p>Structure learning around quick checks and visible progress instead of passive content consumption.</p></article></section>
    <section className="use-cases section-shell"><div><p className="section-label">POSSIBLE USE CASES</p><h2>Designed around the people you need to reach.</h2></div><ul><li><strong>Schools and education teams</strong><span>Make key topics easier to enter in short, repeatable sessions.</span></li><li><strong>Learning and development</strong><span>Turn internal knowledge into a more approachable learning rhythm.</span></li><li><strong>Publishers and experts</strong><span>Explore a focused learning experience around your subject matter.</span></li><li><strong>Communities and brands</strong><span>Help an audience move from viewing content to recalling it.</span></li></ul></section>
    <section className="contact-panel section-shell"><p className="section-label">TELL US WHAT YOU WANT TO BUILD</p><h2>Start with your audience and learning goal.</h2><p>We will use that context to explore whether a customized Krumbit experience is a good fit.</p><a className="primary-link" href="mailto:info@krumbit.co?subject=Custom%20Krumbit%20solution">Contact info@krumbit.co →</a></section><SiteFooter /></main>;
}
