apiVersion: v1
kind: Service
metadata:
  name: krumbit-service
  namespace: easynet
  labels:
    app: krumbit-app
spec:
  type: ClusterIP
  selector:
    app: krumbit-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
