import { AppStoreButton, MobileDownload, SiteFooter, SiteHeader } from "../components/site-chrome";

export const metadata = { title: "Product — How Krumbit Works", description: "Explore Krumbit's short visual lessons, recall quizzes, personalized topics, streaks, and learning progress." };

export default function Product() {
  return <main><SiteHeader />
    <section className="page-hero section-shell"><p className="section-label">PRODUCT</p><h1>Swipe. Recall. Grow.<br /><em>Then get on with your day.</em></h1><p>No hour-long course and no complicated plan. Krumbit is a focused learning loop designed for the spare minutes you already have.</p><AppStoreButton label="Download free on the" /></section>
    <section className="loop-section"><div className="section-shell"><div className="loop-panels"><article className="loop-panel watch-panel"><div className="loop-copy"><span>01 · WATCH</span><h3>One swipe.<br />One useful idea.</h3><p>Visual lessons make science, health, history, technology, and everyday facts easy to enter and quick to finish.</p><ul><li>Short-form video rhythm</li><li>Professionally produced lessons</li><li>Built for spare minutes</li></ul></div><figure className="product-device"><img src="/screen-learn.webp" alt="A bite-sized astronomy lesson in the Krumbit feed" /></figure></article><article className="loop-panel choose-panel"><figure className="product-device"><img src="/screen-topics.webp" alt="Krumbit topic choices and custom topic search" /></figure><div className="loop-copy"><span>02 · CHOOSE</span><h3>Follow a curiosity.<br />Or ask for one.</h3><p>Shape the feed around what you want to understand next instead of accepting whatever an algorithm serves.</p><ul><li>Science, technology, history and more</li><li>Custom topic search</li><li>A feed with a purpose</li></ul></div></article></div><div className="result-pair"><article className="result-card"><div><span>03 · REMEMBER</span><h3>Know what actually stuck.</h3><p>Quick quizzes and learning history turn “I watched it” into “I can explain it.”</p></div><img src="/screen-quiz.webp" alt="Krumbit quiz history" /></article><article className="result-card accent"><div><span>04 · KEEP GOING</span><h3>Make curiosity your streak.</h3><p>XP, gems, levels, and leaderboards give small sessions a reason to become a habit.</p></div><img src="/screen-progress.webp" alt="Krumbit streak and XP progress" /></article></div></div></section>
    <section className="moments section-shell"><div className="section-heading"><p className="section-label">WHEN KRUMBIT FITS</p><h2>The tiny windows where<br /><em>mindless usually wins.</em></h2></div><div className="moment-grid"><article><span>07:42</span><div><small>ON THE COMMUTE</small><h3>Trade three random clips for three things worth knowing.</h3></div></article><article><span>12:18</span><div><small>BETWEEN TASKS</small><h3>Give a five-minute break an ending you feel good about.</h3></div></article><article><span>22:06</span><div><small>BEFORE BED</small><h3>Close the day with curiosity instead of another endless feed.</h3></div></article></div></section>
    <section className="faq section-shell"><div className="section-heading faq-heading"><p className="section-label">QUICK ANSWERS</p><h2>Before your first swipe.</h2></div><div className="faq-list"><details><summary>Is Krumbit free?</summary><p>Krumbit is currently free to download during early access on the App Store.</p></details><details><summary>What can I learn about?</summary><p>Explore science, technology, nature, history, geography, health, and everyday facts—or search for a custom topic.</p></details><details><summary>How long are the lessons?</summary><p>Lessons use the familiar pace of vertical video and are designed for short sessions.</p></details><details><summary>Is it just another video feed?</summary><p>The format is familiar, but every lesson leads into recall, progress, XP, and streaks so watching becomes active learning.</p></details><details><summary>Does it work on iPad?</summary><p>Yes. Krumbit supports iPhone and iPad with iOS or iPadOS 15.1 or later.</p></details></div></section>
    <SiteFooter /><MobileDownload />
  </main>;
}
